// Build root plugin-host.js from modular host source.
// Current stage: legacy single-file source lives at src/host/legacy/plugin-host.js.
// Later stages will compose src/host/*.js modules into this single self-contained
// artifact (required for dynamic Cordis install).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const root = dirname(dirname(fileURLToPath(import.meta.url)));
// The bundle skeleton (the assembled plugin body with all injection markers)
// lives in src/host/app.js; every chunk is injected below.
let body = require('../src/host/app.js');

// Normalize line endings BEFORE marker matching (see build-client.mjs).
body = body.replace(/\r\n/g, '\n');
const pureChunk = require('../src/host/pure.js');
const diagnosticsChunk = require('../src/host/diagnostics.js');
const modelsChunk = require('../src/host/models.js');
const pluginsChunk = require('../src/host/plugins.js');
const updateChunk = require('../src/host/update.js');
const enhanceChunk = require('../src/host/enhance-handlers.js');

// Inject all chunks, looping until no marker remains (same policy as
// build-client.mjs — nested markers get expanded on later passes).
let composed = body;const injections = [
  ['// @dsh-diagnostics-inject', diagnosticsChunk],
  ['// @dsh-models-inject', modelsChunk],
  ['// @dsh-plugins-inject', pluginsChunk],
  ['// @dsh-update-inject', updateChunk],
  ['// @dsh-pure-inject', pureChunk],
  ['// @dsh-enhance-inject', enhanceChunk],
];
let previous;
do {
  previous = composed;
  for (const [marker, chunk] of injections) {
    if (composed.includes(marker)) {
      composed = composed.replace(marker, chunk);
    }
  }
} while (composed !== previous);

// Normalize line endings (see build-client.mjs): source files may carry CRLF
// after a git checkout with core.autocrlf; committed artifacts are LF.
composed = composed.replace(/\r\n/g, '\n');

// Keep the legacy header but mark it as a generated artifact.
const header = `// GENERATED by scripts/build-host.mjs — do not edit by hand.\n// Source: src/host/app.js + src/host/{pure,diagnostics,models,plugins,update,enhance-handlers}.js\n`;
const output = composed.startsWith('// GENERATED') ? composed : header + composed;

mkdirSync(join(root, 'lib'), { recursive: true });
writeFileSync(join(root, 'plugin-host.js'), output, 'utf8');
console.log('plugin-host.js written (' + output.length + ' bytes)');
