// Build lib/client.cjs from plugin-client.js: inlines the dynamic client
// body into the static __ModuleLoader__ bundle. Run: node scripts/build-client.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const root = dirname(dirname(fileURLToPath(import.meta.url)));
// The bundle skeleton (header comments + all injection markers) lives in
// src/client/skeleton.js; every chunk is injected below.
let body = require('../src/client/skeleton.js');

// Normalize line endings BEFORE marker matching: source files may carry CRLF
// (e.g. after a git checkout with core.autocrlf), which would break the
// LF-based marker lookups. Chunks are normalized again at the end so the
// committed artifacts stay byte-stable (LF).
body = body.replace(/\r\n/g, '\n');
const i18nChunk = require('../src/client/i18n.js');
const constantsChunk = require('../src/client/constants.js');
const updaterChunk = require('../src/client/updater.js');
const stateChunk = require('../src/client/state.js');
const helpersChunk = require('../src/client/helpers.js');
const modelHelpersChunk = require('../src/client/model-helpers.js');
const enhanceButtonChunk = require('../src/client/components/enhance-button.js');
const enhanceBarChunk = require('../src/client/components/enhance-bar.js');
const updaterCardChunk = require('../src/client/components/updater-card.js');
const pluginsSectionChunk = require('../src/client/components/plugins-section.js');
const collapsibleSectionChunk = require('../src/client/components/collapsible-section.js');
const modelMainSectionChunk = require('../src/client/components/model-main-section.js');
const fallbackRowChunk = require('../src/client/components/fallback-row.js');
const modelConfigTabChunk = require('../src/client/components/model-config-tab.js');
const paramsTabChunk = require('../src/client/components/params-tab.js');
const modelPluginsSectionChunk = require('../src/client/components/model-plugins-section.js');
const stylesChunk = require('../src/client/styles.js');
const appChunk = require('../src/client/app.js');
// Inject all chunks, looping until no marker remains: component chunks may
// themselves contain other injection markers (e.g. the updater constants
// lived between EnhanceBar and UpdaterCard), so a single pass would leave
// nested markers unexpanded.
const injections = [
  ['// @dsh-client-i18n-inject', i18nChunk],
  ['// @dsh-client-constants-inject', constantsChunk],
  ['// @dsh-client-updater-inject', updaterChunk],
  ['// @dsh-client-state-inject', stateChunk],
  ['// @dsh-client-helpers-inject', helpersChunk],
  ['// @dsh-client-model-helpers-inject', modelHelpersChunk],
  ['// @dsh-client-comp-enhance-button-inject\n', enhanceButtonChunk],
  ['// @dsh-client-comp-enhance-bar-inject\n', enhanceBarChunk],
  ['// @dsh-client-comp-updater-card-inject\n', updaterCardChunk],
  ['// @dsh-client-comp-plugins-section-inject\n', pluginsSectionChunk],
  ['// @dsh-client-comp-collapsible-section-inject\n', collapsibleSectionChunk],
  ['// @dsh-client-comp-model-main-section-inject\n', modelMainSectionChunk],
  ['// @dsh-client-comp-fallback-row-inject\n', fallbackRowChunk],
  ['// @dsh-client-comp-model-config-tab-inject\n', modelConfigTabChunk],
  ['// @dsh-client-comp-params-tab-inject\n', paramsTabChunk],
  ['// @dsh-client-comp-model-plugins-section-inject\n', modelPluginsSectionChunk],
  ['// @dsh-client-styles-inject\n', stylesChunk],
  ['// @dsh-client-app-inject\n', appChunk],
];
let previous;
do {
  previous = body;
  for (const [marker, chunk] of injections) {
    if (body.includes(marker)) {
      body = body.replace(marker, chunk);
    }
  }
} while (body !== previous);

// Final line-ending normalization: chunk files may carry CRLF.
body = body.replace(/\r\n/g, '\n');

// Embed the body as a JSON string literal: safe against backticks, ${}, and
// every other JS metacharacter inside the plugin code.
const embedded = JSON.stringify(body);

const template = `// GENERATED by scripts/build-client.mjs — do not edit by hand.
// Rebuild after changing plugin-client.js: node scripts/build-client.mjs
window.__ModuleLoader__.load({
  id: "dsh-prompt-enhancer",
  factory: (require) => {
    var module = { exports: {} }; var exports = module.exports;
    'use strict';

    const React = require('react');

    // RPC bridge to the host half's harness.handle handlers
    // (registered on /dsh-prompt-enhancer/rpc by lib/index.cjs).
    const host = {
      call(method, args) {
        return fetch('/dsh-prompt-enhancer/rpc', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ method, args: args || {} }),
        }).then((response) => response.json());
      },
    };

    // v2.6.0: bridge to the standalone update executor (lib/updater-host.cjs)
    // on its own port — survives dsh-web restarts; CORS allowed by the executor.
    const executor = {
      call(method, args, port) {
        return fetch('http://127.0.0.1:' + port + '/rpc', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ method, args: args || {} }),
        }).then((response) => response.json());
      },
    };

    // styles facade: inject CSS into a dedicated <style> tag.
    const styles = {
      insert(css) {
        if (document.querySelector('style[data-plugin-css="dsh-prompt-enhancer"]') !== null) return;
        const tag = document.createElement('style');
        tag.dataset.plugin = 'dsh-prompt-enhancer';
        tag.dataset.pluginCss = 'dsh-prompt-enhancer';
        tag.textContent = css;
        document.head.appendChild(tag);
      },
    };

    // Evaluate the dynamic client body (a top-level-return plugin object)
    // with the static environment's symbols closed over.
    const plugin = new Function('React', 'host', 'styles', 'executor', ${embedded})(React, host, styles, executor);

    module.exports = { ...plugin, inject: ['slots', 'locale', 'timer'] };
    return module.exports;
  },
});
`;

mkdirSync(join(root, 'lib'), { recursive: true });
writeFileSync(join(root, 'lib', 'client.cjs'), template, 'utf8');
console.log('lib/client.cjs written (' + template.length + ' bytes)');

// Keep the root plugin-client.js as a committed artifact for dynamic Cordis
// install and for the package "files" list.
const clientHeader = `// GENERATED by scripts/build-client.mjs — do not edit by hand.\n// Source: src/client/skeleton.js + src/client/{i18n,constants,updater,state,helpers,model-helpers,styles,app}.js + src/client/components/*.js\n`;
const clientArtifact = body.startsWith('// GENERATED') ? body : clientHeader + body;
writeFileSync(join(root, 'plugin-client.js'), clientArtifact, 'utf8');
console.log('plugin-client.js written (' + clientArtifact.length + ' bytes)');
