// Build root plugin-host.js from modular host source.
// Current stage: legacy single-file source lives at src/host/legacy/plugin-host.js.
// Later stages will compose src/host/*.js modules into this single self-contained
// artifact (required for dynamic Cordis install).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const root = dirname(dirname(fileURLToPath(import.meta.url)));
const source = join(root, 'src', 'host', 'legacy', 'plugin-host.js');
const body = readFileSync(source, 'utf8');
const pureChunk = require('../src/host/pure.js');
const diagnosticsChunk = require('../src/host/diagnostics.js');

// Inject extracted chunks at the markers left by scripts/extract-*.mjs.
let composed = body;
if (composed.includes('// @dsh-diagnostics-inject')) {
  composed = composed.replace('// @dsh-diagnostics-inject', diagnosticsChunk);
}
if (composed.includes('// @dsh-pure-inject')) {
  composed = composed.replace('// @dsh-pure-inject', pureChunk);
}

// Keep the legacy header but mark it as a generated artifact.
const header = `// GENERATED by scripts/build-host.mjs — do not edit by hand.\n// Source: src/host/legacy/plugin-host.js + src/host/{pure,diagnostics}.js\n`;
const output = composed.startsWith('// GENERATED') ? composed : header + composed;

mkdirSync(join(root, 'lib'), { recursive: true });
writeFileSync(join(root, 'plugin-host.js'), output, 'utf8');
console.log('plugin-host.js written (' + output.length + ' bytes)');
