#!/usr/bin/env node
// ============================================================================
// dsh-prompt-enhancer · prompts 同步脚本
// 把 prompts/*.md（提示词事实源）生成内联到 plugin-host.js 的生成标记区。
//
// 为什么这样做（v2.4.6 设计决策）：
//  - host 半部经 lib/index.cjs 以 new Function('harness', BODY) 执行，动态安装
//    （cordis_define）同样在无 require/fs 的作用域内运行——「运行时读外部文件」
//    在两种安装形态下都不可靠，因此采用「构建时同步」：md 为事实源，脚本生成
//    内联常量，plugin-host.js 保持单文件自包含（动态/静态安装均不受影响）。
//  - 用户可直接编辑 prompts/*.md 后重跑本脚本（node scripts/sync-prompts.mjs），
//    改动随下一次插件发布生效（动插件须重启 GUI）。
//
// 用法: node scripts/sync-prompts.mjs [--check]
//   --check  仅校验生成区与 md 是否一致（不一致退出码 1），不写文件（CI/单测用）
// ============================================================================
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const ROOT = path.resolve(__dirname, '..');
// M1 退役后 app.js 为 bundle 骨架源（build-host.mjs 从它生成 plugin-host.js），
// prompts 生成区位于骨架内——同步目标改为 app.js，避免被 build 覆盖。
const HOST = path.join(ROOT, 'src', 'host', 'app.js');
const BEGIN = '// ==PROMPTS-BEGIN==';
const END = '// ==PROMPTS-END==';

const SOURCES = [
  { md: 'prompts/system.md', name: 'SYSTEM_PROMPT' },
  { md: 'prompts/task-analysis.md', name: 'TASK_ANALYSIS_PROMPT' },
  { md: 'prompts/context-guard.md', name: 'CONTEXT_GUARD' },
  { md: 'prompts/publish.md', name: 'SYSTEM_PUBLISH_PROMPT' },
  // 模式重构（2026-08-16）：会话关联性判定提示词（占位符 {history}/{current} 运行时替换）
  { md: 'prompts/relevance.md', name: 'RELEVANCE_PROMPT' },
  // 模式重构 S3：smart 专业词汇优化段（追加到 smart 模式 system）
  { md: 'prompts/smart.md', name: 'SMART_TAIL_PROMPT' },
  // 模式重构 v2 修订：提示词开发意向判定 + 文档检索/项目地图合并分析（占位符运行时替换）
  { md: 'prompts/intent.md', name: 'DEV_INTENT_PROMPT' },
  { md: 'prompts/doc-analysis.md', name: 'DOC_ANALYSIS_PROMPT' },
  // publish 多步检索（v3.0p）：检索主题规划提示词（占位符 {text}/{memo}/{scenario} 运行时替换）
  { md: 'prompts/websearch.md', name: 'WEBSEARCH_PLAN_PROMPT' },
];

// md 行 → JS 字符串数组元素（转义反斜杠与单引号；行尾空行 trim 掉）
function linesToArray(lines) {
  const arr = [];
  for (const ln of lines) {
    const s = ln.replace(/\r$/, '');
    if (s.trim() === '') { arr.push(''); continue; }
    arr.push(s.replace(/\\/g, '\\\\').replace(/'/g, "\\'"));
  }
  return arr;
}

function buildSection() {
  const blocks = [];
  for (const src of SOURCES) {
    const raw = fs.readFileSync(path.join(ROOT, src.md), 'utf8');
    const lines = raw.split('\n');
    // 去掉文件末尾多余空行（保持 join('\n') 语义与手写版一致）
    while (lines.length > 0 && lines[lines.length - 1].trim() === '') lines.pop();
    if (lines.length === 0) throw new Error(src.md + ' is empty');
    const elems = linesToArray(lines);
    const body = elems.map((e) => '  ' + (e === '' ? "''" : "'" + e + "'")).join(',\n');
    blocks.push('const ' + src.name + ' = [\n' + body + ',\n].join(\'\\n\');');
  }
  return blocks.join('\n\n');
}

const header = [
  BEGIN + '  (generated by scripts/sync-prompts.mjs from prompts/*.md — do not edit here; edit prompts/*.md then rerun)',
  '',
].join('\n');
const footer = END;

// app.js 是 JSON 字符串模块（module.exports = "<转义后的整个 body>"）：生成区文本
// 必须按 JSON 字符串转义形式写入，否则真实换行/引号会破坏字符串字面量。
function escapeForJsonString(text) {
  return JSON.stringify(text).slice(1, -1);
}

const hostSrc = fs.readFileSync(HOST, 'utf8');
// 精确定位生成区：BEGIN 标记带 "(generated by scripts/sync-prompts.mjs" 后缀，
// 与骨架头注释里「plugin-host.js 中 ==PROMPTS-BEGIN== / ==PROMPTS-END== 标记区」
// 的字样区分开（indexOf 裸标记会命中头注释导致替换错位）。
const genBegin = '// ==PROMPTS-BEGIN==  (generated by scripts/sync-prompts.mjs';
const endMarker = '// ==PROMPTS-END==';
const segStart = hostSrc.indexOf(genBegin);
const segEndIdx = hostSrc.indexOf(endMarker, segStart === -1 ? 0 : segStart);
if (segStart === -1 || segEndIdx === -1) {
  console.error('✗ src/host/app.js 缺少生成标记区（' + BEGIN + ' / ' + END + '），请先手工建立');
  process.exit(2);
}
const segEnd = segEndIdx + endMarker.length;
const generated = header + buildSection() + '\n' + footer;
const updated = hostSrc.slice(0, segStart) + escapeForJsonString(generated) + hostSrc.slice(segEnd);

if (updated === hostSrc) {
  console.log('✓ prompts 与 plugin-host.js 生成区一致');
  process.exit(0);
}
if (process.argv.includes('--check')) {
  console.error('✗ 生成区漂移：prompts/*.md 与 plugin-host.js 不一致，请运行 node scripts/sync-prompts.mjs');
  process.exit(1);
}
fs.writeFileSync(HOST, updated, 'utf8');
console.log('✓ plugin-host.js 生成区已同步（' + SOURCES.map((s) => s.name).join('/') + '）');
